export const inventoryItems = [
  {
    id: 1,
    name: 'Steel Bolts',
    quantity: 120,
    location: 'Shelf A1, Bin B1',
    owner: 'John Doe',
    description: 'High-strength steel bolts used for structural assemblies.',
    sku: 'SB-1001',
    category: 'Hardware',
    barcode: '123456789012',
    supplier: 'Steel Co.',
    unitOfMeasure: 'pieces',
    weight: '0.5kg',
    dimensions: '5cm x 2cm x 2cm',
    dateReceived: '2024-09-01',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 50,
    reorderQuantity: 100,
    availability: 'Available',
    costPrice: 0.5,
    sellingPrice: 1.0,
    batchNumber: 'B001',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone A',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Keep dry',
  },
  {
    id: 2,
    name: 'Copper Wire',
    quantity: 250,
    location: 'Shelf B3, Bin C2',
    owner: 'Alice Smith',
    description: 'Flexible copper wire used for electrical applications.',
    sku: 'CW-2034',
    category: 'Electrical',
    barcode: '123456789045',
    supplier: 'Copper Solutions Inc.',
    unitOfMeasure: 'meters',
    weight: '0.02kg per meter',
    dimensions: '100m spool',
    dateReceived: '2024-08-25',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 100,
    reorderQuantity: 200,
    availability: 'Available',
    costPrice: 0.1,
    sellingPrice: 0.25,
    batchNumber: 'B002',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone B',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Avoid exposure to moisture',
  },
  {
    id: 3,
    name: 'Aluminum Sheets',
    quantity: 75,
    location: 'Shelf C1, Bin D2',
    owner: 'Beta LLC',
    description:
      'Lightweight aluminum sheets for industrial and construction use.',
    sku: 'AS-3012',
    category: 'Metals',
    barcode: '123456789078',
    supplier: 'AluTech',
    unitOfMeasure: 'sheets',
    weight: '1.5kg',
    dimensions: '2m x 1m',
    dateReceived: '2024-09-01',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 30,
    reorderQuantity: 60,
    availability: 'Available',
    costPrice: 15.0,
    sellingPrice: 25.0,
    batchNumber: 'B003',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone C',
    returnStatus: 'Non-returnable',
    handlingInstructions: 'Handle with care',
  },
  {
    id: 4,
    name: 'Ceramic Tiles',
    quantity: 300,
    location: 'Shelf D4, Bin A1',
    owner: 'Acme Corp.',
    description: 'Durable ceramic tiles for flooring and walls.',
    sku: 'CT-4021',
    category: 'Construction',
    barcode: '123456789099',
    supplier: 'TileMasters',
    unitOfMeasure: 'pieces',
    weight: '0.8kg',
    dimensions: '30cm x 30cm',
    dateReceived: '2024-08-20',
    expirationDate: null,
    lastUpdated: '2024-09-07',
    status: 'In Stock',
    reorderLevel: 100,
    reorderQuantity: 200,
    availability: 'Available',
    costPrice: 2.5,
    sellingPrice: 4.0,
    batchNumber: 'B004',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone D',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Fragile',
  },
  {
    id: 5,
    name: 'Industrial Lubricant',
    quantity: 100,
    location: 'Shelf E2, Bin B3',
    owner: 'John Doe',
    description: 'High-grade lubricant for heavy machinery.',
    sku: 'IL-5002',
    category: 'Chemicals',
    barcode: '123456789123',
    supplier: 'LubriMax',
    unitOfMeasure: 'liters',
    weight: '1kg',
    dimensions: '1L bottle',
    dateReceived: '2024-07-25',
    expirationDate: '2025-07-25',
    lastUpdated: '2024-09-06',
    status: 'In Stock',
    reorderLevel: 50,
    reorderQuantity: 100,
    availability: 'Available',
    costPrice: 12.0,
    sellingPrice: 18.0,
    batchNumber: 'B005',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone E',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a cool, dry place',
  },
  {
    id: 6,
    name: 'Stainless Steel Screws',
    quantity: 500,
    location: 'Shelf F3, Bin C1',
    owner: 'Alice Smith',
    description: 'Corrosion-resistant stainless steel screws for outdoor use.',
    sku: 'SS-6013',
    category: 'Hardware',
    barcode: '123456789134',
    supplier: 'ScrewMasters',
    unitOfMeasure: 'pieces',
    weight: '0.02kg',
    dimensions: '3cm x 0.5cm',
    dateReceived: '2024-09-05',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 200,
    reorderQuantity: 400,
    availability: 'Available',
    costPrice: 0.15,
    sellingPrice: 0.3,
    batchNumber: 'B006',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone F',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a dry place',
  },
  {
    id: 7,
    name: 'Rubber Seals',
    quantity: 300,
    location: 'Shelf G1, Bin D3',
    owner: 'Beta LLC',
    description: 'Durable rubber seals for plumbing and mechanical use.',
    sku: 'RS-7025',
    category: 'Seals',
    barcode: '123456789156',
    supplier: 'SealPro',
    unitOfMeasure: 'pieces',
    weight: '0.1kg',
    dimensions: '5cm diameter',
    dateReceived: '2024-09-02',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 100,
    reorderQuantity: 200,
    availability: 'Available',
    costPrice: 0.2,
    sellingPrice: 0.5,
    batchNumber: 'B007',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone G',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a dry place',
  },
  {
    id: 8,
    name: 'Electrical Fuses',
    quantity: 150,
    location: 'Shelf H2, Bin A2',
    owner: 'Acme Corp.',
    description: 'Electrical fuses for circuit protection.',
    sku: 'EF-8032',
    category: 'Electrical',
    barcode: '123456789167',
    supplier: 'FuseCo',
    unitOfMeasure: 'pieces',
    weight: '0.05kg',
    dimensions: '5cm x 1cm',
    dateReceived: '2024-08-30',
    expirationDate: null,
    lastUpdated: '2024-09-07',
    status: 'In Stock',
    reorderLevel: 50,
    reorderQuantity: 100,
    availability: 'Available',
    costPrice: 0.3,
    sellingPrice: 0.6,
    batchNumber: 'B008',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone H',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a dry place',
  },
  {
    id: 9,
    name: 'Hydraulic Hoses',
    quantity: 80,
    location: 'Shelf I1, Bin B2',
    owner: 'John Doe',
    description: 'Heavy-duty hydraulic hoses for fluid transfer.',
    sku: 'HH-9011',
    category: 'Hydraulics',
    barcode: '123456789178',
    supplier: 'HydroTech',
    unitOfMeasure: 'meters',
    weight: '0.5kg per meter',
    dimensions: '50m coil',
    dateReceived: '2024-08-15',
    expirationDate: null,
    lastUpdated: '2024-09-06',
    status: 'In Stock',
    reorderLevel: 30,
    reorderQuantity: 60,
    availability: 'Available',
    costPrice: 5.0,
    sellingPrice: 8.0,
    batchNumber: 'B009',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone I',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Avoid exposure to sunlight',
  },
  {
    id: 10,
    name: 'Safety Goggles',
    quantity: 150,
    location: 'Shelf J2, Bin C1',
    owner: 'Alice Smith',
    description: 'Protective safety goggles for eye protection.',
    sku: 'SG-1023',
    category: 'Safety',
    barcode: '123456789189',
    supplier: 'SafetyGear',
    unitOfMeasure: 'pieces',
    weight: '0.2kg',
    dimensions: 'Standard size',
    dateReceived: '2024-08-20',
    expirationDate: null,
    lastUpdated: '2024-09-07',
    status: 'In Stock',
    reorderLevel: 50,
    reorderQuantity: 100,
    availability: 'Available',
    costPrice: 3.0,
    sellingPrice: 6.0,
    batchNumber: 'B010',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone J',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a clean, dry place',
  },
  {
    id: 11,
    name: 'Power Tools',
    quantity: 35,
    location: 'Shelf K1, Bin D2',
    owner: 'Beta LLC',
    description: 'Versatile power tools for various applications.',
    sku: 'PT-2045',
    category: 'Tools',
    barcode: '123456789190',
    supplier: 'ToolMasters',
    unitOfMeasure: 'pieces',
    weight: '3kg',
    dimensions: 'Various sizes',
    dateReceived: '2024-08-10',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 20,
    reorderQuantity: 40,
    availability: 'Available',
    costPrice: 50.0,
    sellingPrice: 75.0,
    batchNumber: 'B011',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone K',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Handle with care',
  },
  {
    id: 12,
    name: 'LED Light Bulbs',
    quantity: 500,
    location: 'Shelf L2, Bin A3',
    owner: 'Acme Corp.',
    description: 'Energy-efficient LED light bulbs for general use.',
    sku: 'LB-3056',
    category: 'Lighting',
    barcode: '123456789201',
    supplier: 'BrightLights',
    unitOfMeasure: 'pieces',
    weight: '0.1kg',
    dimensions: 'Standard size',
    dateReceived: '2024-09-01',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 200,
    reorderQuantity: 400,
    availability: 'Available',
    costPrice: 1.0,
    sellingPrice: 2.0,
    batchNumber: 'B012',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone L',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Keep away from moisture',
  },
  {
    id: 13,
    name: 'Pneumatic Pumps',
    quantity: 60,
    location: 'Shelf M1, Bin C2',
    owner: 'John Doe',
    description: 'Pneumatic pumps for fluid transfer applications.',
    sku: 'PP-4067',
    category: 'Pneumatics',
    barcode: '123456789212',
    supplier: 'PneumaTech',
    unitOfMeasure: 'pieces',
    weight: '2kg',
    dimensions: '20cm x 15cm',
    dateReceived: '2024-07-30',
    expirationDate: null,
    lastUpdated: '2024-09-06',
    status: 'In Stock',
    reorderLevel: 25,
    reorderQuantity: 50,
    availability: 'Available',
    costPrice: 25.0,
    sellingPrice: 35.0,
    batchNumber: 'B013',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone M',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Keep dry and clean',
  },
  {
    id: 14,
    name: 'Welding Rods',
    quantity: 100,
    location: 'Shelf N2, Bin B1',
    owner: 'Alice Smith',
    description: 'High-quality welding rods for metal joining.',
    sku: 'WR-5078',
    category: 'Welding',
    barcode: '123456789223',
    supplier: 'WeldMaster',
    unitOfMeasure: 'pieces',
    weight: '0.4kg',
    dimensions: '30cm length',
    dateReceived: '2024-08-10',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 40,
    reorderQuantity: 80,
    availability: 'Available',
    costPrice: 2.0,
    sellingPrice: 4.0,
    batchNumber: 'B014',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone N',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a dry place',
  },
  {
    id: 15,
    name: 'Paint Thinner',
    quantity: 90,
    location: 'Shelf O3, Bin A2',
    owner: 'Beta LLC',
    description: 'Solvent used for thinning paint and cleaning.',
    sku: 'PT-6089',
    category: 'Chemicals',
    barcode: '123456789234',
    supplier: 'PaintCo',
    unitOfMeasure: 'liters',
    weight: '1kg per liter',
    dimensions: '5L can',
    dateReceived: '2024-08-20',
    expirationDate: '2025-08-20',
    lastUpdated: '2024-09-06',
    status: 'In Stock',
    reorderLevel: 30,
    reorderQuantity: 60,
    availability: 'Available',
    costPrice: 8.0,
    sellingPrice: 12.0,
    batchNumber: 'B015',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone O',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a cool, well-ventilated area',
  },
  {
    id: 16,
    name: 'Metal Brackets',
    quantity: 200,
    location: 'Shelf P1, Bin B3',
    owner: 'Acme Corp.',
    description: 'Steel brackets for supporting and mounting structures.',
    sku: 'MB-7090',
    category: 'Hardware',
    barcode: '123456789245',
    supplier: 'BracketWorks',
    unitOfMeasure: 'pieces',
    weight: '0.2kg',
    dimensions: '10cm x 5cm',
    dateReceived: '2024-09-01',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 100,
    reorderQuantity: 200,
    availability: 'Available',
    costPrice: 1.5,
    sellingPrice: 3.0,
    batchNumber: 'B016',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone P',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Keep dry',
  },
  {
    id: 17,
    name: 'Air Filters',
    quantity: 75,
    location: 'Shelf Q2, Bin C1',
    owner: 'John Doe',
    description: 'Air filters for HVAC systems.',
    sku: 'AF-8012',
    category: 'HVAC',
    barcode: '123456789256',
    supplier: 'FilterCo',
    unitOfMeasure: 'pieces',
    weight: '0.5kg',
    dimensions: '30cm x 30cm',
    dateReceived: '2024-07-15',
    expirationDate: '2025-07-15',
    lastUpdated: '2024-09-07',
    status: 'In Stock',
    reorderLevel: 40,
    reorderQuantity: 80,
    availability: 'Available',
    costPrice: 5.0,
    sellingPrice: 8.0,
    batchNumber: 'B017',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone Q',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a dry place',
  },
  {
    id: 18,
    name: 'Cable Ties',
    quantity: 300,
    location: 'Shelf R3, Bin A1',
    owner: 'Alice Smith',
    description: 'Durable cable ties for securing cables and wires.',
    sku: 'CT-9023',
    category: 'Electrical',
    barcode: '123456789267',
    supplier: 'TieMaster',
    unitOfMeasure: 'pieces',
    weight: '0.05kg',
    dimensions: '20cm length',
    dateReceived: '2024-08-05',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 100,
    reorderQuantity: 200,
    availability: 'Available',
    costPrice: 0.1,
    sellingPrice: 0.25,
    batchNumber: 'B018',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone R',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Keep away from sunlight',
  },
  {
    id: 19,
    name: 'Laser Cutters',
    quantity: 15,
    location: 'Shelf S1, Bin B2',
    owner: 'Beta LLC',
    description: 'High-precision laser cutters for metal and plastic.',
    sku: 'LC-1034',
    category: 'Machinery',
    barcode: '123456789278',
    supplier: 'LaserTech',
    unitOfMeasure: 'pieces',
    weight: '10kg',
    dimensions: '50cm x 50cm',
    dateReceived: '2024-06-25',
    expirationDate: null,
    lastUpdated: '2024-09-07',
    status: 'In Stock',
    reorderLevel: 10,
    reorderQuantity: 20,
    availability: 'Available',
    costPrice: 500.0,
    sellingPrice: 750.0,
    batchNumber: 'B019',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone S',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Handle with care',
  },
  {
    id: 20,
    name: 'Insulation Tape',
    quantity: 120,
    location: 'Shelf T2, Bin C3',
    owner: 'Acme Corp.',
    description: 'Electrical insulation tape for wire and cable protection.',
    sku: 'IT-2045',
    category: 'Electrical',
    barcode: '123456789289',
    supplier: 'TapeWorks',
    unitOfMeasure: 'rolls',
    weight: '0.1kg per roll',
    dimensions: '10m roll',
    dateReceived: '2024-08-25',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 50,
    reorderQuantity: 100,
    availability: 'Available',
    costPrice: 1.0,
    sellingPrice: 2.5,
    batchNumber: 'B020',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone T',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Keep away from high temperatures',
  },
  {
    id: 21,
    name: 'Steel Plates',
    quantity: 45,
    location: 'Shelf T3, Bin B2',
    owner: 'John Doe',
    description: 'Heavy-duty steel plates for construction.',
    sku: 'SP-3015',
    category: 'Metals',
    barcode: '123456789289',
    supplier: 'SteelWorks',
    unitOfMeasure: 'plates',
    weight: '5kg',
    dimensions: '1m x 1m',
    dateReceived: '2024-08-20',
    expirationDate: null,
    lastUpdated: '2024-09-06',
    status: 'In Stock',
    reorderLevel: 20,
    reorderQuantity: 40,
    availability: 'Available',
    costPrice: 50.0,
    sellingPrice: 75.0,
    batchNumber: 'B020',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone T',
    returnStatus: 'Non-returnable',
    handlingInstructions: 'Handle with care',
  },
  {
    id: 22,
    name: 'Gasket Sets',
    quantity: 80,
    location: 'Shelf U1, Bin C2',
    owner: 'Alice Smith',
    description: 'Complete sets of gaskets for various engines.',
    sku: 'GS-4092',
    category: 'Automotive',
    barcode: '123456789290',
    supplier: 'GasketPros',
    unitOfMeasure: 'sets',
    weight: '1kg',
    dimensions: 'Set box',
    dateReceived: '2024-09-05',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 30,
    reorderQuantity: 60,
    availability: 'Available',
    costPrice: 12.0,
    sellingPrice: 18.0,
    batchNumber: 'B021',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone U',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a dry place',
  },
  {
    id: 23,
    name: 'Electric Motors',
    quantity: 30,
    location: 'Shelf V2, Bin D3',
    owner: 'Beta LLC',
    description: 'High-efficiency electric motors for various applications.',
    sku: 'EM-5094',
    category: 'Electronics',
    barcode: '123456789301',
    supplier: 'MotorTech',
    unitOfMeasure: 'pieces',
    weight: '4kg',
    dimensions: '30cm x 20cm',
    dateReceived: '2024-07-20',
    expirationDate: null,
    lastUpdated: '2024-09-06',
    status: 'In Stock',
    reorderLevel: 15,
    reorderQuantity: 30,
    availability: 'Available',
    costPrice: 100.0,
    sellingPrice: 150.0,
    batchNumber: 'B022',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone V',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Keep dry and away from moisture',
  },
  {
    id: 24,
    name: 'Paint Brushes',
    quantity: 200,
    location: 'Shelf W3, Bin A1',
    owner: 'Acme Corp.',
    description: 'High-quality paint brushes for precision painting.',
    sku: 'PB-6083',
    category: 'Painting',
    barcode: '123456789312',
    supplier: 'BrushWorks',
    unitOfMeasure: 'pieces',
    weight: '0.05kg',
    dimensions: 'Various sizes',
    dateReceived: '2024-08-30',
    expirationDate: null,
    lastUpdated: '2024-09-07',
    status: 'In Stock',
    reorderLevel: 100,
    reorderQuantity: 200,
    availability: 'Available',
    costPrice: 2.0,
    sellingPrice: 4.0,
    batchNumber: 'B023',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone W',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Keep clean and dry',
  },
  {
    id: 25,
    name: 'Metal Shelving Units',
    quantity: 20,
    location: 'Shelf X1, Bin B2',
    owner: 'John Doe',
    description: 'Sturdy metal shelving units for storage.',
    sku: 'MS-7095',
    category: 'Furniture',
    barcode: '123456789323',
    supplier: 'ShelfMasters',
    unitOfMeasure: 'units',
    weight: '25kg',
    dimensions: '2m x 1m x 0.5m',
    dateReceived: '2024-08-05',
    expirationDate: null,
    lastUpdated: '2024-09-06',
    status: 'In Stock',
    reorderLevel: 10,
    reorderQuantity: 20,
    availability: 'Available',
    costPrice: 75.0,
    sellingPrice: 120.0,
    batchNumber: 'B024',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone X',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Assemble carefully',
  },
  {
    id: 26,
    name: 'Rubber Hoses',
    quantity: 100,
    location: 'Shelf Y1, Bin C3',
    owner: 'Alice Smith',
    description: 'Durable rubber hoses for fluid transfer.',
    sku: 'RH-5096',
    category: 'Plumbing',
    barcode: '123456789334',
    supplier: 'HoseCo',
    unitOfMeasure: 'meters',
    weight: '0.2kg per meter',
    dimensions: '50m roll',
    dateReceived: '2024-09-01',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 40,
    reorderQuantity: 80,
    availability: 'Available',
    costPrice: 2.0,
    sellingPrice: 3.5,
    batchNumber: 'B025',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone Y',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Avoid extreme temperatures',
  },
  {
    id: 27,
    name: 'Digital Multimeters',
    quantity: 15,
    location: 'Shelf Z2, Bin A4',
    owner: 'Beta LLC',
    description: 'Digital multimeters for measuring electrical parameters.',
    sku: 'DM-7038',
    category: 'Electronics',
    barcode: '123456789345',
    supplier: 'ElectroTools',
    unitOfMeasure: 'pieces',
    weight: '0.5kg',
    dimensions: '15cm x 10cm',
    dateReceived: '2024-07-25',
    expirationDate: null,
    lastUpdated: '2024-09-07',
    status: 'In Stock',
    reorderLevel: 10,
    reorderQuantity: 20,
    availability: 'Available',
    costPrice: 30.0,
    sellingPrice: 45.0,
    batchNumber: 'B026',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone Z',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Handle with care',
  },
  {
    id: 28,
    name: 'Toolboxes',
    quantity: 40,
    location: 'Shelf A1, Bin B3',
    owner: 'Acme Corp.',
    description: 'Heavy-duty toolboxes for various tools.',
    sku: 'TB-8095',
    category: 'Tools',
    barcode: '123456789356',
    supplier: 'ToolMasters',
    unitOfMeasure: 'pieces',
    weight: '3kg',
    dimensions: '40cm x 20cm x 20cm',
    dateReceived: '2024-08-15',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 20,
    reorderQuantity: 40,
    availability: 'Available',
    costPrice: 40.0,
    sellingPrice: 60.0,
    batchNumber: 'B027',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone A',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a dry place',
  },
  {
    id: 29,
    name: 'Screws and Nails Assortment',
    quantity: 150,
    location: 'Shelf B2, Bin C1',
    owner: 'John Doe',
    description: 'Assorted screws and nails for various applications.',
    sku: 'SNA-9043',
    category: 'Hardware',
    barcode: '123456789367',
    supplier: 'FastenersInc',
    unitOfMeasure: 'pieces',
    weight: '1kg',
    dimensions: 'Container box',
    dateReceived: '2024-08-10',
    expirationDate: null,
    lastUpdated: '2024-09-06',
    status: 'In Stock',
    reorderLevel: 50,
    reorderQuantity: 100,
    availability: 'Available',
    costPrice: 15.0,
    sellingPrice: 25.0,
    batchNumber: 'B028',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone B',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Keep dry',
  },
  {
    id: 30,
    name: 'Machine Filters',
    quantity: 80,
    location: 'Shelf C3, Bin A2',
    owner: 'Alice Smith',
    description: 'Filters for various types of machinery.',
    sku: 'MF-6015',
    category: 'Machinery',
    barcode: '123456789378',
    supplier: 'FilterCo',
    unitOfMeasure: 'pieces',
    weight: '0.5kg',
    dimensions: 'Box of filters',
    dateReceived: '2024-09-05',
    expirationDate: null,
    lastUpdated: '2024-09-07',
    status: 'In Stock',
    reorderLevel: 30,
    reorderQuantity: 60,
    availability: 'Available',
    costPrice: 20.0,
    sellingPrice: 30.0,
    batchNumber: 'B029',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone C',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Keep in a clean environment',
  },
  {
    id: 31,
    name: 'Industrial Adhesives',
    quantity: 70,
    location: 'Shelf D4, Bin B2',
    owner: 'Beta LLC',
    description: 'High-strength adhesives for industrial use.',
    sku: 'IA-4078',
    category: 'Chemicals',
    barcode: '123456789389',
    supplier: 'AdhesiveMasters',
    unitOfMeasure: 'bottles',
    weight: '0.3kg',
    dimensions: '500ml bottle',
    dateReceived: '2024-07-30',
    expirationDate: '2025-07-30',
    lastUpdated: '2024-09-06',
    status: 'In Stock',
    reorderLevel: 40,
    reorderQuantity: 80,
    availability: 'Available',
    costPrice: 10.0,
    sellingPrice: 15.0,
    batchNumber: 'B030',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone D',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Keep sealed and away from heat',
  },
  {
    id: 32,
    name: 'Car Battery Chargers',
    quantity: 25,
    location: 'Shelf E2, Bin C1',
    owner: 'Acme Corp.',
    description: 'Chargers for car batteries.',
    sku: 'CBC-5124',
    category: 'Automotive',
    barcode: '123456789390',
    supplier: 'ChargeTech',
    unitOfMeasure: 'pieces',
    weight: '1.5kg',
    dimensions: '20cm x 15cm',
    dateReceived: '2024-08-01',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 10,
    reorderQuantity: 25,
    availability: 'Available',
    costPrice: 40.0,
    sellingPrice: 60.0,
    batchNumber: 'B031',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone E',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Avoid moisture',
  },
  {
    id: 33,
    name: 'Screwdriver Sets',
    quantity: 40,
    location: 'Shelf F3, Bin A1',
    owner: 'John Doe',
    description: 'Various types of screwdrivers in a set.',
    sku: 'SS-1023',
    category: 'Tools',
    barcode: '123456789401',
    supplier: 'ToolMasters',
    unitOfMeasure: 'sets',
    weight: '1kg',
    dimensions: 'Set box',
    dateReceived: '2024-08-25',
    expirationDate: null,
    lastUpdated: '2024-09-07',
    status: 'In Stock',
    reorderLevel: 20,
    reorderQuantity: 40,
    availability: 'Available',
    costPrice: 30.0,
    sellingPrice: 45.0,
    batchNumber: 'B032',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone F',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a dry place',
  },
  {
    id: 34,
    name: 'Safety Helmets',
    quantity: 90,
    location: 'Shelf G1, Bin B3',
    owner: 'Alice Smith',
    description: 'Protective helmets for safety in hazardous areas.',
    sku: 'SH-2056',
    category: 'Safety',
    barcode: '123456789412',
    supplier: 'SafetyGear',
    unitOfMeasure: 'pieces',
    weight: '0.7kg',
    dimensions: 'One size',
    dateReceived: '2024-08-12',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 40,
    reorderQuantity: 80,
    availability: 'Available',
    costPrice: 15.0,
    sellingPrice: 25.0,
    batchNumber: 'B033',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone G',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Keep away from chemicals',
  },
  {
    id: 35,
    name: 'Drill Bits',
    quantity: 60,
    location: 'Shelf H4, Bin A3',
    owner: 'Beta LLC',
    description: 'Assorted drill bits for various drilling needs.',
    sku: 'DB-9087',
    category: 'Tools',
    barcode: '123456789423',
    supplier: 'DrillMasters',
    unitOfMeasure: 'pieces',
    weight: '0.2kg',
    dimensions: 'Box of bits',
    dateReceived: '2024-07-20',
    expirationDate: null,
    lastUpdated: '2024-09-06',
    status: 'In Stock',
    reorderLevel: 30,
    reorderQuantity: 60,
    availability: 'Available',
    costPrice: 25.0,
    sellingPrice: 35.0,
    batchNumber: 'B034',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone H',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Keep dry and clean',
  },
  {
    id: 36,
    name: 'Work Gloves',
    quantity: 120,
    location: 'Shelf J2, Bin C2',
    owner: 'John Doe',
    description: 'Protective gloves for work purposes.',
    sku: 'WG-3045',
    category: 'Safety',
    barcode: '123456789434',
    supplier: 'GloveMasters',
    unitOfMeasure: 'pairs',
    weight: '0.3kg',
    dimensions: 'Standard size',
    dateReceived: '2024-09-01',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 50,
    reorderQuantity: 100,
    availability: 'Available',
    costPrice: 8.0,
    sellingPrice: 12.0,
    batchNumber: 'B035',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone J',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a cool, dry place',
  },
  {
    id: 37,
    name: 'Cordless Drills',
    quantity: 18,
    location: 'Shelf K1, Bin A2',
    owner: 'Acme Corp.',
    description: 'Cordless drills with rechargeable batteries.',
    sku: 'CD-5048',
    category: 'Tools',
    barcode: '123456789445',
    supplier: 'DrillMasters',
    unitOfMeasure: 'pieces',
    weight: '1.2kg',
    dimensions: '20cm x 25cm',
    dateReceived: '2024-08-18',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 10,
    reorderQuantity: 20,
    availability: 'Available',
    costPrice: 70.0,
    sellingPrice: 100.0,
    batchNumber: 'B036',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone K',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Avoid moisture and extreme temperatures',
  },
  {
    id: 38,
    name: 'Workbench',
    quantity: 10,
    location: 'Shelf L1, Bin B4',
    owner: 'John Doe',
    description: 'Heavy-duty workbench for workshop use.',
    sku: 'WB-1012',
    category: 'Tools',
    barcode: '123456789456',
    supplier: 'ToolMasters',
    unitOfMeasure: 'pieces',
    weight: '25kg',
    dimensions: '120cm x 60cm x 90cm',
    dateReceived: '2024-08-20',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 5,
    reorderQuantity: 10,
    availability: 'Available',
    costPrice: 200.0,
    sellingPrice: 300.0,
    batchNumber: 'B037',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone L',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a dry place',
  },
  {
    id: 39,
    name: 'Laser Levels',
    quantity: 25,
    location: 'Shelf M2, Bin A4',
    owner: 'Acme Corp.',
    description: 'Laser levels for precise measurements.',
    sku: 'LL-2022',
    category: 'Tools',
    barcode: '123456789467',
    supplier: 'LevelMasters',
    unitOfMeasure: 'pieces',
    weight: '0.8kg',
    dimensions: '15cm x 10cm',
    dateReceived: '2024-08-30',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 15,
    reorderQuantity: 30,
    availability: 'Available',
    costPrice: 50.0,
    sellingPrice: 70.0,
    batchNumber: 'B038',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone M',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Handle with care',
  },
  {
    id: 40,
    name: 'Portable Generators',
    quantity: 8,
    location: 'Shelf N1, Bin B2',
    owner: 'Beta LLC',
    description: 'Generators for portable power needs.',
    sku: 'PG-7054',
    category: 'Generators',
    barcode: '123456789478',
    supplier: 'PowerGen',
    unitOfMeasure: 'pieces',
    weight: '25kg',
    dimensions: '60cm x 45cm x 45cm',
    dateReceived: '2024-08-25',
    expirationDate: null,
    lastUpdated: '2024-09-07',
    status: 'In Stock',
    reorderLevel: 5,
    reorderQuantity: 10,
    availability: 'Available',
    costPrice: 500.0,
    sellingPrice: 700.0,
    batchNumber: 'B039',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone N',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a dry place',
  },
  {
    id: 41,
    name: 'Electric Saws',
    quantity: 12,
    location: 'Shelf O1, Bin C3',
    owner: 'Acme Corp.',
    description: 'Electric saws for cutting wood and metal.',
    sku: 'ES-3012',
    category: 'Tools',
    barcode: '123456789489',
    supplier: 'SawTech',
    unitOfMeasure: 'pieces',
    weight: '4kg',
    dimensions: '30cm x 20cm x 15cm',
    dateReceived: '2024-08-05',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 8,
    reorderQuantity: 15,
    availability: 'Available',
    costPrice: 150.0,
    sellingPrice: 200.0,
    batchNumber: 'B040',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone O',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Handle with care',
  },
  {
    id: 42,
    name: 'Welding Masks',
    quantity: 25,
    location: 'Shelf P3, Bin B1',
    owner: 'Beta LLC',
    description: 'Protective masks for welding operations.',
    sku: 'WM-1024',
    category: 'Safety',
    barcode: '123456789490',
    supplier: 'SafetyGear',
    unitOfMeasure: 'pieces',
    weight: '0.6kg',
    dimensions: 'Standard size',
    dateReceived: '2024-09-01',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 15,
    reorderQuantity: 30,
    availability: 'Available',
    costPrice: 25.0,
    sellingPrice: 35.0,
    batchNumber: 'B041',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone P',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Keep clean and dry',
  },
  {
    id: 43,
    name: 'Hydraulic Jacks',
    quantity: 10,
    location: 'Shelf Q2, Bin A5',
    owner: 'John Doe',
    description: 'Hydraulic jacks for lifting heavy loads.',
    sku: 'HJ-2047',
    category: 'Automotive',
    barcode: '123456789501',
    supplier: 'LiftTech',
    unitOfMeasure: 'pieces',
    weight: '8kg',
    dimensions: '40cm x 25cm x 25cm',
    dateReceived: '2024-08-22',
    expirationDate: null,
    lastUpdated: '2024-09-07',
    status: 'In Stock',
    reorderLevel: 5,
    reorderQuantity: 10,
    availability: 'Available',
    costPrice: 120.0,
    sellingPrice: 180.0,
    batchNumber: 'B042',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone Q',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a dry place',
  },
  {
    id: 44,
    name: 'Pressure Washers',
    quantity: 7,
    location: 'Shelf R1, Bin C2',
    owner: 'Acme Corp.',
    description: 'High-pressure washers for cleaning surfaces.',
    sku: 'PW-3028',
    category: 'Cleaning Equipment',
    barcode: '123456789512',
    supplier: 'CleanTech',
    unitOfMeasure: 'pieces',
    weight: '15kg',
    dimensions: '50cm x 40cm x 35cm',
    dateReceived: '2024-08-10',
    expirationDate: null,
    lastUpdated: '2024-09-07',
    status: 'In Stock',
    reorderLevel: 3,
    reorderQuantity: 10,
    availability: 'Available',
    costPrice: 300.0,
    sellingPrice: 450.0,
    batchNumber: 'B043',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone R',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Keep away from moisture',
  },
  {
    id: 45,
    name: 'Electric Drills',
    quantity: 20,
    location: 'Shelf S2, Bin B4',
    owner: 'Beta LLC',
    description: 'Electric drills for various drilling tasks.',
    sku: 'ED-4056',
    category: 'Tools',
    barcode: '123456789523',
    supplier: 'DrillMasters',
    unitOfMeasure: 'pieces',
    weight: '1.5kg',
    dimensions: '25cm x 20cm x 15cm',
    dateReceived: '2024-08-15',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 10,
    reorderQuantity: 20,
    availability: 'Available',
    costPrice: 80.0,
    sellingPrice: 110.0,
    batchNumber: 'B044',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone S',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a dry place',
  },
  {
    id: 46,
    name: 'Heat Guns',
    quantity: 18,
    location: 'Shelf T3, Bin A1',
    owner: 'John Doe',
    description: 'Heat guns for various heating applications.',
    sku: 'HG-5098',
    category: 'Tools',
    barcode: '123456789534',
    supplier: 'HeatTech',
    unitOfMeasure: 'pieces',
    weight: '1kg',
    dimensions: '20cm x 15cm x 10cm',
    dateReceived: '2024-09-01',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 10,
    reorderQuantity: 20,
    availability: 'Available',
    costPrice: 60.0,
    sellingPrice: 90.0,
    batchNumber: 'B045',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone T',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Avoid extreme temperatures',
  },
  {
    id: 47,
    name: 'Power Tools Set',
    quantity: 6,
    location: 'Shelf U2, Bin B3',
    owner: 'Acme Corp.',
    description: 'Set of power tools for various applications.',
    sku: 'PTS-6019',
    category: 'Tools',
    barcode: '123456789545',
    supplier: 'ToolMasters',
    unitOfMeasure: 'sets',
    weight: '5kg',
    dimensions: 'Case of tools',
    dateReceived: '2024-09-03',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 5,
    reorderQuantity: 10,
    availability: 'Available',
    costPrice: 250.0,
    sellingPrice: 350.0,
    batchNumber: 'B046',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone U',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a dry place',
  },
  {
    id: 48,
    name: 'Car Washing Kits',
    quantity: 12,
    location: 'Shelf V3, Bin C2',
    owner: 'John Doe',
    description: 'Kits for washing cars, including brushes and soaps.',
    sku: 'CWK-3025',
    category: 'Automotive',
    barcode: '123456789556',
    supplier: 'CleanAuto',
    unitOfMeasure: 'kits',
    weight: '3kg',
    dimensions: 'Kit box',
    dateReceived: '2024-08-28',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 6,
    reorderQuantity: 15,
    availability: 'Available',
    costPrice: 45.0,
    sellingPrice: 70.0,
    batchNumber: 'B047',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone V',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a cool, dry place',
  },
  {
    id: 49,
    name: 'Inspection Mirrors',
    quantity: 30,
    location: 'Shelf W4, Bin A2',
    owner: 'Beta LLC',
    description: 'Mirrors for inspecting hard-to-reach areas.',
    sku: 'IM-2048',
    category: 'Tools',
    barcode: '123456789567',
    supplier: 'MirrorTech',
    unitOfMeasure: 'pieces',
    weight: '0.5kg',
    dimensions: '20cm x 20cm',
    dateReceived: '2024-09-02',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 20,
    reorderQuantity: 40,
    availability: 'Available',
    costPrice: 30.0,
    sellingPrice: 45.0,
    batchNumber: 'B048',
    serialNumber: null,
    warehouse: 'Warehouse 1',
    condition: 'New',
    pickZone: 'Zone W',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Handle with care',
  },
  {
    id: 50,
    name: 'Tool Sets',
    quantity: 8,
    location: 'Shelf X1, Bin B5',
    owner: 'Acme Corp.',
    description: 'Complete tool sets for various tasks.',
    sku: 'TS-8090',
    category: 'Tools',
    barcode: '123456789578',
    supplier: 'ToolMasters',
    unitOfMeasure: 'sets',
    weight: '10kg',
    dimensions: 'Toolbox size',
    dateReceived: '2024-09-07',
    expirationDate: null,
    lastUpdated: '2024-09-08',
    status: 'In Stock',
    reorderLevel: 4,
    reorderQuantity: 8,
    availability: 'Available',
    costPrice: 200.0,
    sellingPrice: 280.0,
    batchNumber: 'B049',
    serialNumber: null,
    warehouse: 'Warehouse 2',
    condition: 'New',
    pickZone: 'Zone X',
    returnStatus: 'Eligible for return',
    handlingInstructions: 'Store in a dry place',
  },
];
